# Generated by Django 3.0.4 on 2020-03-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/images/default.svg', upload_to='blog/images'),
        ),
    ]
